### ISSUE TITLE
Environment "example" should support UTF-8

### ISSUE THREAD

**Issue by koppor** [cgnieder/cnltx#5] opened 2020-05-18 19:57 UTC
I would like to use UTF-8 in the `example` environment:

```latex
\documentclass{article}
\usepackage{cnltx-example}
\begin{document}
Mögen
\begin{example}
  Mögen
\end{example}
\end{document}
```

The umlaut is killed:

![grafik](https://user-images.githubusercontent.com/1366654/82253926-34c64b00-9952-11ea-83e6-a88073d667d0.png)

I did not found documentation in "cnltx_en.pdf". Just found an `inputenc` statement (which is is not requried in texlive 2019 and later --> UTF-8 is default encoding since mid 2018: https://github.com/latex3/latex2e/issues/24).

![grafik](https://user-images.githubusercontent.com/1366654/82254116-91296a80-9952-11ea-941f-13c306d19440.png)

**Comment by cgnieder** [comment] 2020-05-19 07:26
This is a duplicate of issue #3 – the answer basically is: there is no solution for pdfLaTeX. With LuaLaTeX the following works:

```latex
\documentclass{article}
\usepackage{cnltx-example}
\setcnltx{add-listings-options={literate=}}
\begin{document}
Mögen
\begin{example}
  Mögen
\end{example}
\end{document}
```

**Closed by cgnieder** 2020-05-19 07:26 UTC
Labels: duplicate

**Comment by koppor** [comment] 2020-05-19 08:39
Yeah, works. (Just searched for "UTF" in the GitHub issue search, not for "umlauts".)

![grafik](https://user-images.githubusercontent.com/1366654/82304683-eb5f1580-99bc-11ea-8b3f-08da359380d8.png)

`pdflatex` output: (just for the googlers)

```text
! Package inputenc Error: Invalid UTF-8 byte sequence.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.7   M├Âgen
```
